services:
  api:
    build: .
    restart: always
    volumes:
      - ./html:/var/www/html
    ports:
      - "80:8080"
  database:
    image: postgres:alpine3.19
    environment:
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=hugedata
    volumes:
      - ./database:/docker-entrypoint-initdb.d/

